language: node_js
node_js:
  - "6"
  
branches:
  only:
  - master

nstall:
  - npm -g install yarn
  - yarn

before_script:
  - npm prune

script:
  - npm run test

notifications:
  email: false